version: '2'

services:
  web:
    build: .
    image: test
    command: bash -c 'npm install && npm run watch'
    working_dir: /app/local
    volumes:
      - '.:/app/local'

  app:
    build: .
    image: pineauth
    command: 'amber watch'
    working_dir: /app/local
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/pineauth_development
      SMTP_URL: mail:1025
    ports:
      - '3000:3000'
    depends_on:
      - db
      - mail
    volumes:
      - '.:/app/local'

  migrate:
    build: .
    image: pineauth
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done && amber db migrate seed'
    working_dir: /app/local
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/pineauth_development
    volumes:
      - '.:/app/local'
    links:
      - db

  mail:
    image: drujensen/mailcatcher:latest
    ports:
      - '1080:1080'

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pineauth_development
    volumes:
      - 'db:/var/lib/postgres/data'

volumes:
  db:
